steps:
- name: 'gpii/exekube:0.4.0-google'
  id: 'terraform-fmt-check'
  entrypoint: 'sh'
  waitFor: ['-']
  args:
    - '-c'
    - |
      echo "Running Terraform format check..."
      terraform fmt --check=true /workspace
  timeout: 120s
- name: 'gpii/exekube:0.4.0-google'
  id: 'gcp-unit-tests'
  entrypoint: 'sh'
  waitFor: ['-']
  args:
    - '-c'
    - |
      echo "Running GCP unit tests..."
      cd /workspace/shared/rakefiles/tests
      gem install bundler --no-ri --no-rdoc
      bundle install --path "vendor/bundle"
      rake
  timeout: 120s
- name: 'gpii/exekube:0.4.0-google'
  id: 'aws-unit-tests'
  entrypoint: 'sh'
  waitFor: ['-']
  args:
    - '-c'
    - |
      echo "Running AWS unit tests..."
      cd /workspace/aws/rakefiles/tests
      gem install test-unit --no-ri --no-rdoc
      rake
  timeout: 120s
options:
  logging: GCS_ONLY
  logStreamingOption: STREAM_ON
  logsBucket: gs://gpii-gcp-dev-natarajaya-build-logs
