clusterSize: ${replica_count}

adminUsername: ${couchdb_admin_username}
adminPassword: ${couchdb_admin_password}
cookieAuthSecret: ${couchdb_auth_cookie}

persistentVolume:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  storageClass: "standard"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: "app"
              operator: In
              values:
              - couchdb
        topologyKey: "kubernetes.io/hostname"

couchdbConfig:
  chttpd:
    bind_address: any
    # http://docs.couchdb.org/en/stable/config/auth.html#authentication-configuration
    require_valid_user: true

resources:
  requests:
    cpu: ${requests_cpu}
    memory: ${requests_memory}
  limits:
    cpu: ${limits_cpu}
    memory: ${limits_memory}
